### PR TITLE
Update to 2.4.3

### PR DESCRIPTION
**Pull request by Eonfge**
Does not include GNOME update. For that, see here: https://github.com/flathub/net.poedit.Poedit/pull/23

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build

**Comment by Eonfge** [comment]
bot, build

---
Weird error though

**Comment by Eonfge** [comment]
@bilelmoussaoui Would it still be possible to update this application, although it uses GNOME 3.36?

**Comment by cho2** [comment]
I built 2.4.3 with 3.36 runtime on #25, but 3.36 runtime no longer exist (end-of-life)

**Comment by Eonfge** [comment]
Ow, I had not seen you tried 3.36 first.

let's hope that @bilelmoussaoui can help us here, because this is rather inconvinient

**Comment by bilelmoussaoui** [comment]
The only way to help you here is by trying to figure out how to bump the runtime to at least 3.38

**Comment by Eonfge** [comment]
bot, build

It's a shame because I rather not disable warning, but this should do it.

**Comment by hfiguiere** [comment]
> bot, build
> 
> It's a shame because I rather not disable warning, but this should do it.

The warning doesn't fix the broken code, so it doesn't change much and allow building.

**Comment by cho2** [comment]
LGTM

Cuplikan layar dari 2021-05-04 09-08-47

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
