### PR TITLE
Update to 2.3

### PR DESCRIPTION
**Pull request by cho2**
Update to 2.3

### CODE REVIEW

**Comment by cho2** [comment]
@bilelmoussaoui can you take a look?

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Mind updating the appdata patch to bump the version number? :) otherwise I can take care of that

**Comment by cho2** [comment]
> Mind updating the appdata patch to bump the version number? :) otherwise I can take care of that

@bilelmoussaoui 
https://github.com/flathub/net.poedit.Poedit/pull/13/commits/68ec80de82b3f53c2fbe4718128d9986880c81fe

**Comment by bilelmoussaoui** [comment]
Thanks a lot @cho2

**Pull request merged**
