### PR TITLE
update to 2.2.3

### PR DESCRIPTION
**Pull request by cho2**
update to 2.2.3

### CODE REVIEW

**Comment by cho2** [comment]
```
flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/net.poedit.Poedit.appdata.xml
 in dir /srv/buildbot/worker/build-x86_64-7/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run org.freedesktop.appstream-glib validate builddir/*/share/appdata/net.poedit.Poedit.appdata.xml'
 using PTY: False
builddir/files/share/appdata/net.poedit.Poedit.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• tag-missing           : <release> required
Validation of files failed
program finished with exit code 1
elapsedTime=1.457995
```

**Comment by cho2** [comment]
@bilelmoussaoui can you take a look?

**Comment by bilelmoussaoui** [comment]
The appdata file lacks the oars and releases tags. Can you patch it here and send the patch upstream please? Otherwise I can take care of it later this week

**Comment by cho2** [comment]
noted

**Comment by bilelmoussaoui** [comment]
Took over this here #10. Will send that patch upstream as soon as I can. Closing this, thanks!

**Pull request closed without merging**
