### PR TITLE
update poedit to 3.0

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
The build fail because it need `wxWebview`. I'm not sure how it is supposed to be provided but my guess would be with GtkWebKit that mean moving to the GNOME SDK, but I don't see evidence of the wxWidget configure trying to detect it.

**Comment by vslavik** [comment]
>  but I don't see evidence of the wxWidget configure trying to detect it. 

That's because it's currently explicitly disabled in the build file: https://github.com/flathub/net.poedit.Poedit/blob/4050eab7c02b3fb14e25cc6633b35fc58339d1d0/net.poedit.Poedit.json#L34-L35

Here's corresponding change in snap build when this dependency was added:
https://github.com/vslavik/poedit/commit/3463a2e5830b1af0c2800edd0d8775ef0defc8cd#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5

And wxWidgets uses webkit2gtk for implementation (with GTK+ 3, which I assume you use as well):

https://github.com/wxWidgets/wxWidgets/blob/05f36c4819c63f7e4e8b7833e44570fe136e0a9f/configure.in#L7471-L7472

**Comment by hfiguiere** [comment]
That mean switching to use the GNOME SDK to get it. (shouldn't be an issue)

@cho2 do you mind fixing this? It's your PR

**Comment by cho2** [comment]
bot, build net.poedit.Poedit

**Comment by cho2** [comment]
@flathub/reviewers

**Pull request merged**
